### ISSUE TITLE
MPRIS Installation Failing

### ISSUE THREAD

**Issue by corbin-auriti** [twolfson/google-music-electron#25] opened 2015-11-26 18:37 UTC
Here is the output from the terminal http://pastebin.com/91bnHdnL
And here is the output from npm-debug.log http://pastebin.com/ZWuRHiC0

**Comment by twolfson** [comment] 2015-11-27 00:50
Hmmm, not too sure what's going on here. What were the commands you used to initially install `google-music-electron` (e.g. with `sudo`) and install MPRIS?

**Comment by corbin-auriti** [comment] 2015-11-27 01:53
I installed it initially with "sudo npm install -g google-music-electron" which went fine, then "sudo google-music-electron install-mpris" which failed

**Comment by twolfson** [comment] 2015-11-27 04:08
Alright, let's make sure this isn't a permissioning issue. Can you clone the repo, install its dependencies, and try the MPRIS install?

``` bash
# Clone the repository
git clone https://github.com/twolfson/google-music-electron
cd google-music-electron

# Install our dependencies and dev dependencies
npm install

# Install MPRIS
bin/google-music-electron install-mpris

# Run our application
npm start
```

**Comment by RavetcoFX** [comment] 2015-11-27 07:26
Nope, that still fails, http://pastebin.com/wzJJSjDr
My knowledge of npm, so I'm not even sure were to start debugging this

**Comment by corbin-auriti** [comment] 2015-11-27 07:29
Nope, that still fails, http://pastebin.com/wzJJSjDr
My knowledge of npm, so I'm not even sure were to start debugging this

npm_debug.log http://pastebin.com/TWaD0hpb

**Comment by twolfson** [comment] 2015-11-27 15:25
It looks like the issue is occurring during the compilation of the `dbus` connection. I'm not sure whether "No such file or directory" corresponds to `g++` not existing or the `include/node` not existing. Can you verify that you have `g++` installed (e.g. run `which g++`)? 

```
make: Entering directory `/home/ravetcofx/Downloads/Untitled Folder/google-music-electron/node_modules/mpris-service/node_modules/dbus/build'
  CXX(target) Release/obj.target/dbus/src/dbus.o
make: Leaving directory `/home/ravetcofx/Downloads/Untitled Folder/google-music-electron/node_modules/mpris-service/node_modules/dbus/build'

g++: error: Folder/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.4/include/node: No such file or directory
g++: error: Folder/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.4/src: No such file or directory
g++: error: Folder/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.4/deps/uv/include: No such file or directory
g++: error: Folder/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.4/deps/v8/include: No such file or directory
make: *** [Release/obj.target/dbus/src/dbus.o] Error 1
```

**Comment by corbin-auriti** [comment] 2015-11-27 18:34
I have /usr/bin/g++
is there a specific package that deals with the dbus connection in npm?

**Comment by twolfson** [comment] 2015-11-28 18:46
I think it's solely g++ for node-gyp. Can you verify g++ can be resolved as sudo? `sudo which g++`

**Comment by corbin-auriti** [comment] 2015-11-28 20:14
Yup, I'm also getting /usr/bin/g++ in sudo

**Comment by twolfson** [comment] 2015-11-29 06:59
Ah, maybe you are missing some of the `dbus` dependenices. Can you verify all of this is configured properly?

https://github.com/Shouqun/node-dbus/tree/f9239298fe14c992df2c16ddc2f53864225dcf3a#dependencies

**Comment by rossabaker** [comment] 2015-12-15 03:45
I had the same ELIFECYCLE error tonight as the first post.  I followed the instructions from [this comment](https://github.com/twolfson/google-music-electron/issues/22#issuecomment-150839683) to upgrade electron-prebuilt.  Replacing `0.26.1` with `0.36.0`, everything works for me again.

**Comment by twolfson** [comment] 2015-12-15 06:05
Awesome, thanks for the info @rossabaker :+1:

**Comment by urandom** [comment] 2015-12-26 21:53
It seems some people have been able to install the mpris service, but I wasn't able to. My gme install was clean, but the mpris stuff failed:

```
3627 silly install generateActionsToTake
3628 verbose stack TypeError: Cannot read property 'target' of null
3628 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
3628 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3628 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3628 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3628 verbose stack     at Object.Installer.computeLinked (/usr/lib/node_modules/npm/lib/install.js:411:41)
3628 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3628 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3628 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3628 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
3628 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3629 verbose cwd /usr/lib/node_modules/google-music-electron
3630 error Linux 4.2.5-1-ARCH
3631 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--ignore-scripts" "--save" "false" "electron-rebuild@~1.0.2" "mpris-service@~1.0.1"
3632 error node v5.3.0
3633 error npm  v3.5.2
3634 error Cannot read property 'target' of null
3635 error If you need help, you may report this error at:
3635 error     <https://github.com/npm/npm/issues>
```

**Comment by twolfson** [comment] 2015-12-26 22:02
I have noticed some issues in `npm@3.x.x` (e.g. https://github.com/npm/npm/issues/10119). Can you downgrade to `npm@2.x.x` and see if that resolves the issue?

``` bash
npm install -g npm@latest-2
# or npm install -g npm@2.x.x
```

**Comment by urandom** [comment] 2015-12-26 22:21
With npm2, I get a whole different set of errors. First, I get a bunch of permission denied errors, even though I use `sudo google-music-electron install-mpris` .  If I make /usr/lib/node_modules/google-music-electron/node_modules/electron-prebuilt/ world writable, I end up with the next error:
`ETXTBSY: text file is busy, open '/usr/lib/node_modules/google-music-electron/node_modules/electron-prebuilt/dist/electron'`

**Comment by twolfson** [comment] 2015-12-26 22:36
Weird, I have never seen `ETXTBSY` before. Are you running in a VM or is `google-music-electron` already running? (i.e. we are trying to overwrite the `electron` executable when installing MPRIS)

**Comment by urandom** [comment] 2015-12-26 23:12
Neither of those, and to be honest I didn't think that error would be possible under linux

**Comment by twolfson** [comment] 2015-12-26 23:16
Ahhh, I think I have it. We are using `electron` as our CLI parser for the `install-mpris` subcommand. According the `access(2)` man page this is what is likely causing the issue:

http://linux.die.net/man/2/access

Although, it's very strange that no other Linux instances had this issue before. For our reference, what OS are you running?

I will take a look at breaking out that script by the end of next weekend.

**Comment by twolfson** [comment] 2015-12-26 23:19
As a workaround for the meantime, you can get a local copy set up via the following instructions:

``` bash
# Clone our repo
git clone https://github.com/twolfson/google-music-electron
cd google-music-electron

# Install our dependencies,
#   install `mprisDependencies` (typically via custom script),
#   and run `electron-rebuild`
npm install
npm install --ignore-scripts --save false electron-rebuild@~0.2.5 mpris-service@~1.0.1
./node_modules/electron-rebuild/lib/cli.js

# Our local `google-music-electron` should be all set with MPRIS
node bin/google-music-electron

# Or link it globally and use it on the CLI
npm link
google-music-electron
```

**Comment by corbin-auriti** [comment] 2015-12-27 03:18
Sorry, I've been a bit busy lately, but I'll go through everything and test later today and report back

**Comment by urandom** [comment] 2015-12-27 16:10
Running ./node_modules/electron-rebuild/lib/cli.js first produces a bunch of permission denied errors
 since apparently running that thing with sudo drops the privileges. Once you give write access to everyone in the electron-prebuilt directory, it proceeds.

However, using 0.2.5 doesn't build for node 5.3. Using the latest electron-prebuilt works fine

**Comment by twolfson** [comment] 2015-12-27 23:40
Oh, whoops. Yea, that's an old version of dependencies. I copy/pasted from another issue =/ It should be these 2 (as you discovered):

https://github.com/twolfson/google-music-electron/blob/2.5.1/package.json#L52-L53

``` bash
# Clone our repo
git clone https://github.com/twolfson/google-music-electron
cd google-music-electron

# Install our dependencies,
#   install `mprisDependencies` (typically via custom script),
#   and run `electron-rebuild`
npm install
npm install --ignore-scripts --save false electron-rebuild@~1.0.2 mpris-service@~1.0.1
./node_modules/electron-rebuild/lib/cli.js

# Our local `google-music-electron` should be all set with MPRIS
node bin/google-music-electron

# Or link it globally and use it on the CLI
npm link
google-music-electron
```

**Comment by twolfson** [comment] 2015-12-30 03:04
Alright, I have created a patch branch but before landing it, I want to make sure it works. @urandom Can you try out the following code:

``` bash
# Clone our repo
git clone https://github.com/twolfson/google-music-electron
cd google-music-electron

# Check out the patched branch
git checkout dev/breakout.mpris.command

# Install our dependencies
npm install

# Install MPRIS
node bin/google-music-electron.js install-mpris

# Launch google-music-electron
node bin/google-music-electron.js
```

**Comment by urandom** [comment] 2015-12-30 08:38
Hi, this seems to install fine. The only question is whether it will install properly globally, without any 'permission denied' errors. But if that occurs, I can open another, smaller issue just for that problem.

**Comment by twolfson** [comment] 2015-12-30 17:47
Hooray! I will release this by the end of the weekend.

With respect to permissioning issues, `npm` suggests letting `/usr/local/lib/node_modules` be owned by `$USER`:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by twolfson** [comment] 2015-12-31 03:43
Alright, the `install-mpris` location has been released in `2.6.0`. @urandom You should be able to upgrade globally via:

``` bash
npm install -g google-music-electron@latest
```

**Comment by urandom** [comment] 2016-01-01 12:06
> With respect to permissioning issues, npm suggests letting /usr/local/lib/node_modules be owned by $USER:

This is a very bad suggestion. It might be ok to set the ownership of just node_modules  to your user, even though that in itself sounds very bad, however linking will fail. But setting up bin and share to your user is just an awful suggestion, and it doesn't speak well of this npmjs if that's their official solution...

**Comment by twolfson** [comment] 2016-01-01 22:25
It's mostly to avoid using `sudo` all the time. If you are still having problems with `sudo`, then please open another issue so we can discuss there.

**Comment by twolfson** [comment] 2016-02-05 23:09
I think this issue has been resolved, closing due to inactivity outside of that.

**Closed as completed by twolfson** 2016-02-05 23:09 UTC
Labels: bug
