### ISSUE TITLE
Can't install mpris after 1.20.0

### ISSUE THREAD

**Issue by rossabaker** [twolfson/google-music-electron#22] opened 2015-10-24 05:32 UTC
I admit to not knowing what I'm doing in node.

```
% google-music-electron install-mpris    
npm WARN package.json google-music-electron@2.0.0 No license field.
mpris-service@1.0.3 node_modules/mpris-service
└── dbus@0.2.12 (nan@1.9.0)

electron-rebuild@0.2.5 node_modules/electron-rebuild
├── ncp@2.0.0
├── promise@7.0.4 (asap@2.0.3)
├── nslog@2.0.0 (nan@1.6.1)
├── rimraf@2.4.3 (glob@5.0.15)
├── lodash@3.10.1
├── yargs@3.29.0 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.2, y18n@3.2.0, os-locale@1.4.0, cliui@3.0.3)
├── npm@2.14.8
└── babel-core@5.8.25 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-eval@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-undefined-to-void@1.1.6, babel-plugin-react-constant-elements@1.0.3, babel-plugin-member-expression-literals@1.0.1, shebang-regex@1.0.0, trim-right@1.0.1, path-is-absolute@1.0.0, to-fast-properties@1.0.1, babel-plugin-react-display-name@1.0.3, path-exists@1.0.0, babel-plugin-constant-folding@1.0.1, fs-readdir-recursive@0.1.2, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.1, line-numbers@0.2.0, home-or-tmp@1.0.0, debug@2.2.0, chalk@1.1.1, minimatch@2.0.10, babel-plugin-undeclared-variables-check@1.0.2, is-integer@1.0.6, repeating@1.1.3, detect-indent@3.0.1, babylon@5.8.23, resolve@1.1.6, output-file-sync@1.1.1, source-map@0.4.4, bluebird@2.10.2, source-map-support@0.2.10, json5@0.4.0, regexpu@1.3.0, core-js@1.2.3, regenerator@0.8.35)

> electron-prebuilt@0.34.1 postinstall /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.34.1-linux-x64.zip
[============================================>] 100.0% of 36.67 MB (5.24 MB/s)

> dbus@0.2.12 install /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/mpris-service/node_modules/dbus
> node-gyp configure build

make: Entering directory '/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/mpris-service/node_modules/dbus/build'
  CXX(target) Release/obj.target/dbus/src/dbus.o
dbus.target.mk:104: recipe for target 'Release/obj.target/dbus/src/dbus.o' failed
make: Leaving directory '/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/mpris-service/node_modules/dbus/build'

In file included from ../src/dbus.cc:7:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/dbus.cc:7:
/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.1/src/node_buffer.h:41:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.1/src/node_buffer.h:41:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/dbus.cc:7:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/dbus.cc:7:
/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.1/src/node_buffer.h:53:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.34.1/src/node_buffer.h:53:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/dbus.cc:7:0:
../node_modules/nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/dbus/src/dbus.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "node" "/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/mpris-service/node_modules/dbus
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "node" "/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.34.1" "--arch=x64"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! dbus@0.2.12 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dbus@0.2.12 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/electron-rebuild/lib/spawn.js:53:26)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
MPRIS integration successfully installed! Please start `google-music-electron` to see it in action!
```

0.20.0 installs fine...

```
% google-music-electron install-mpris        
[14879:1024/013057:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
npm WARN package.json google-music-electron@1.20.0 No license field.
mpris-service@1.0.3 node_modules/mpris-service
└── dbus@0.2.12 (nan@1.9.0)

electron-rebuild@0.2.5 node_modules/electron-rebuild
├── ncp@2.0.0
├── promise@7.0.4 (asap@2.0.3)
├── nslog@2.0.0 (nan@1.6.1)
├── lodash@3.10.1
├── rimraf@2.4.3 (glob@5.0.15)
├── yargs@3.29.0 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.2, y18n@3.2.0, os-locale@1.4.0, cliui@3.0.3)
├── babel-core@5.8.25 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-eval@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-undefined-to-void@1.1.6, babel-plugin-react-constant-elements@1.0.3, babel-plugin-member-expression-literals@1.0.1, shebang-regex@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, babel-plugin-react-display-name@1.0.3, babel-plugin-constant-folding@1.0.1, fs-readdir-recursive@0.1.2, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.1, babel-plugin-undeclared-variables-check@1.0.2, line-numbers@0.2.0, home-or-tmp@1.0.0, is-integer@1.0.6, repeating@1.1.3, debug@2.2.0, minimatch@2.0.10, chalk@1.1.1, babylon@5.8.23, detect-indent@3.0.1, source-map@0.4.4, resolve@1.1.6, output-file-sync@1.1.1, bluebird@2.10.2, source-map-support@0.2.10, json5@0.4.0, regexpu@1.3.0, core-js@1.2.3, regenerator@0.8.35)
└── npm@2.14.8
MPRIS integration successfully installed! Please start `google-music-electron` to see it in action!
```

... however it doesn't seem to work:

```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.google-music-electron /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'  
method return time=1445664798.895287 sender=:1.89 -> destination=:1.143 serial=16 reply_serial=2
   variant       array [
      ]
```

Apologies for not being able to dig myself.  I had this working at one point, and it was a better Linux experience than the native Spotify.  Thank you for the great work.

**Comment by twolfson** [comment] 2015-10-24 05:42
In `1.21.0` we upgraded to `electron@0.34.0`. I am betting this has to do something with that. From a quick triage, it looks like there's an upgraded version of `electron-rebuild` so upgrading to that might fix everything.

https://github.com/twolfson/google-music-electron/blob/2.0.0/CHANGELOG.md

https://github.com/twolfson/google-music-electron/blob/2.0.0/package.json#L56-L59

https://github.com/electronjs/electron-rebuild/tree/1.0.2

I am heads down at the moment but should be able to try to reproduce/patch soon (if not with respect to "soon", I will let you know).

**Comment by twolfson** [comment] 2015-10-24 06:36
Looking into this now. I have successfully reproduced the issue :tada:

**Comment by twolfson** [comment] 2015-10-24 06:38
Damn, upgrading `electron-rebuild` seems to have not patched it =(

**Comment by twolfson** [comment] 2015-10-24 06:42
Downgrading to `electron-prebuild@0.33.9` didn't work either. Looking into `mpris-service` and `dbus`

**Comment by twolfson** [comment] 2015-10-24 06:44
Likely relevant: `electron-prebuilt@0.31.0` upgraded to Chrome 44 and `iojs@3.1.0`.

https://github.com/atom/electron/releases/tag/v0.31.0

**Comment by twolfson** [comment] 2015-10-24 06:48
`electron-prebuilt@0.30.x` works, `0.31.x`/`0.32.x` seem to hard exit without doing anything.

**Comment by twolfson** [comment] 2015-10-24 06:55
Hmmm, so I upgraded `nan` (cross version native bindings abstraction) inside of `node_modules/mpris-service/node_modules/dbus` and I get a different error but I think `dbus` needs patches itself:

```
/home/todd/github/google-music-electron/node_modules/electron-rebuild/lib/headers/.node-gyp/0.33.9/src/node.h:240:13: note:   template argument deduction/substitution failed:
../src/dbus.cc:333:60: note:   cannot convert ‘Signal::EmitSignal’ (type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
   NODE_SET_METHOD(exports, "emitSignal", Signal::EmitSignal);
```

**Comment by twolfson** [comment] 2015-10-24 07:15
Alright, I have concluded that the issue is `dbus` not being on the latest `nan`. It looks like things were mostly interface changes but I don't know C++ so I am getting frustrated while attempting to patch it.

As a result, I am going to open an issue and request that we stick to `google-music-electron@1.20.0` for MPRIS support for now. In my opinion, the `electron-prebuilt` upgrade has higher precedence as it unbroke some things which were broken on Windows.

For reference, to downgrade to `google-electron-music@1.20.0` we can run:

``` bash
npm install google-music-electron@1.20.0 -g
```

**Comment by twolfson** [comment] 2015-10-24 07:18
For reference, here's the `node-dbus` issue: https://github.com/Shouqun/node-dbus/issues/105

**Comment by rossabaker** [comment] 2015-10-24 14:31
Thank you so much!  I can see the mpris interface in 1.20.0, but the controls don't work and the metadata is not returned.  I suspect it's related to these uncaught errors:

```
[24722:1024/102005:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
2015-10-24T14:20:06.224Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "/home/ross/.config/google-music-electron/verbose.log"
2015-10-24T14:20:06.309Z - info: App ready. Opening Google Music window height=920, icon=/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/lib/assets/icon-32.png, preload=/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/lib/browser.js, skip-taskbar=undefined, use-content-size=true, width=1024, http_parser=2.3.0, node=1.6.3, v8=4.2.77.15, uv=1.4.2, zlib=1.2.8, ares=1.10.0-DEV, modules=43, openssl=1.0.1m, electron=0.26.1, atom-shell=0.26.1, chrome=42.0.2311.107, version=1.20.0
[24722:1024/102011:INFO:CONSOLE(443)] "Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.", source: /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/google-music/lib/main.js (443)
[24722:1024/102014:INFO:CONSOLE(318)] "Uncaught TypeError: Cannot read property 'contains' of undefined", source: /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/google-music/lib/main.js (318)
[24722:1024/102015:INFO:CONSOLE(318)] "Uncaught TypeError: Cannot read property 'contains' of undefined", source: /home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/node_modules/google-music/lib/main.js (318)
```

When I upgrade back to 2.0.0, these errors disappear.  So I'm somewhat optimistic that full mpris functionality will return once that node-dbus issue is resolved.

```
2015-10-24T14:22:27.160Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "/home/ross/.config/google-music-electron/verbose.log"
2015-10-24T14:22:27.322Z - info: App ready. Opening Google Music window height=920, icon=/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/lib/assets/icon-32.png, preload=/home/ross/.nvm/versions/node/v0.12.7/lib/node_modules/google-music-electron/lib/browser.js, skip-taskbar=undefined, use-content-size=true, width=1024, http_parser=2.5.0, node=4.1.1, v8=4.5.103.29, uv=1.7.4, zlib=1.2.8, ares=1.10.1-DEV, modules=46, openssl=1.0.2d, electron=0.34.1, atom-shell=0.34.1, chrome=45.0.2454.85, version=2.0.0
```

**Comment by rossabaker** [comment] 2015-10-24 14:39
I built 1.20.0 locally with electron=0.30.8 to see whether its newer Chrome (43.0.2357.65) would work around those errors.  Same uncaught errors, same dead mpris interface.

**Comment by rossabaker** [comment] 2015-10-24 15:06
On a whim, I tried 2.0.0 with downgraded electron.  That also installs with mpris, but fails right at startup.

```
Uncaught Exception:
TypeError: Cannot read property 'apply' of undefined
    at Object.<anonymous> (/home/ross/src/personal/google-music-electron/node_modules/monogamous/dist/monogamous.js:190:33)
    at EventEmitter.handleReady (/home/ross/src/personal/google-music-electron/lib/google-music-electron.js:331:12)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

No huge surprise there.  Now seeing if I can make any sense of the C++.

**Comment by rossabaker** [comment] 2015-10-24 16:14
Well, I got dbus compiling against nan-2.1.0: Shouqun/node-dbus#106

I don't yet understand the node toolset well enough to make the install-mpris command use my patched copy.  I have tried copying my version into the mpris-service directory, installing a dbus 0.2.12-ross, and other variations, and it keeps trying to compile the official dbus 0.2.12.

**Comment by twolfson** [comment] 2015-10-24 18:28
Wow, nice! That PR definitely looks better than what I would have come up with ;)

As far as the other comments on this thread, I will talk about them 1 by 1.

With respect to `google-music-electron@1.20.0`. Ah so I totally read the start of this issue wrong -- I thought you were saying `1.20.0` was your last known stable version. Since I might be making assumptions, did MPRIS ever fully run locally on any version? If so, what version?

With respect to trying downgraded `electron's`, previous to this last upgrade we were running against `0.26.1`.

https://github.com/twolfson/google-music-electron/blob/1.19.1/package.json#L39

As a result, I would suggest trying to compile with that locally (so you have something working until `dbus` is sorted out). Here are the steps to doing that:

``` bash
# Clone the repo
git clone https://github.com/twolfson/google-music-electron
cd google-music-electron

# Install our dependencies
npm install

# Override `electron-prebuilt` with our preferred version and update the `package.json`
npm install electron-prebuilt@~0.26.1 --save

# Install MPRIS
node bin/google-music-electron install-mpris

# Launch google-music-electron locally
node bin/google-music-electron

# Link our local repo to the global node modules
# (i.e. treat local directory as if it were globally installed via `npm install -g`)
# DEV: Please try to avoid using `sudo` with this command
#    it will lead to `root` owned local node modules folders
#    Workarounds are here: https://docs.npmjs.com/getting-started/fixing-npm-permissions
npm link

# CLI `google-music-electron` will now reference local directory's version
google-music-electron
```

**Comment by twolfson** [comment] 2015-10-24 18:46
As for linking up `dbus` to `google-music-electron`, we can leverage `npm link` again. It doubles as a system for connecting packages to each other during development.

https://docs.npmjs.com/cli/link

Here are the steps for setting up `google-music-electron` to compile with an altered version of `mpris-service` and `dbus`:

``` bash
# Clone all our repos
git clone https://github.com/twolfson/google-music-electron
git clone https://github.com/emersion/mpris-service
git clone https://github.com/Shouqun/node-dbus

# Navigate to our `dbus` repo, checkout your branch, and link it globally
cd node-dbus
git checkout <branch>  # Please update this with your branch
npm install # Install dependencies and build local version
npm link  # Once again, please don't use this with `sudo` or things will get effed =/

# Navigate to `mpris-service`, install its dependencies,
#   override its dbus with our new dbus, and link it globally
cd ../mpris-service
npm install
npm link node-dbus

# Navigate to `google-music-electron`, install its dependencies,
#   install `mprisDependencies` (typically via custom script),
#   link our custom `mpris-service`,
#   and run `electron-rebuild`
cd ../google-music-electron
npm install
npm install --ignore-scripts --save false electron-rebuild@~0.2.5 mpris-service@~1.0.1
npm link mpris-service
./node_modules/electron-rebuild/lib/cli.js

# Our local `google-music-electron` should be all set with MPRIS
node bin/google-music-electron

# Or link it globally and use it on the CLI
npm link
google-music-electron
```

Reference links:
- Typical custom script done via `google-music-electron mpris-install`
  - https://github.com/twolfson/google-music-electron/blob/2.0.0/lib/google-music-electron.js#L51-L80
  - Runs `npm install with`mprisDependencies` written out
    - https://github.com/twolfson/google-music-electron/blob/2.0.0/package.json#L56-L59
  - Runs `electron-rebuild/lib/cli.js`

**Comment by twolfson** [comment] 2015-10-24 18:55
A couple more things, while writing up the next set of comments, I used our about dialog and noticed `node` version was missing from it. Upon inspecting `process.versions`, it looks like our `electron` is running `4.1.1` under the hood -_-;;

I am going to cut a new release that include the `node` version in the about window.

```
ares: "1.10.1-DEV"
atom-shell: "0.33.9"
chrome: "45.0.2454.85"
electron: "0.33.9"
http_parser: "2.5.0"
modules: "46"
node: "4.1.1"
openssl: "1.0.2d"
uv: "1.7.4"
v8: "4.5.103.29"
zlib: "1.2.8"
```

Additional notes:
- While developing on `node-dbus`, be sure to use the same version of `iojs`/`node` that `electron` will be using. It looks like you are using `nvm` so this can be done via:
  - `nvm install 4.1.1`
  - Then we can rebuild `node-dbus` on that version via its `npm install` command
- As noted during the initial debugging, there is a new major version of `electron-rebuild`. If things are still looking bad with respect to `mpris-service`, then maybe try upgrading `electron-rebuild` as well.
  - This can be done by modifying the semver in `package.json's mprisDependencies` key
  - https://github.com/twolfson/google-music-electron/blob/2.0.0/package.json#L56-L59

**Comment by rossabaker** [comment] 2015-10-24 19:44
Thank you for the handholding.  I'm getting closer.  This is the first Node work I've ever done.

I had a fully working version, but was too careless to note which.  I'm guessing, based on dates, it was 1.19.0.  I noticed that my mpris had stopped working, figured it was a breaking change on Google's end, saw you had been busy, so I tried to upgrade.  After running into the dbus issue on 2.0.0, I determined out that mpris would install if I downgraded back to 1.20.0.  And then I saw it still didn't work.

Your suggestion [here](https://github.com/twolfson/google-music-electron/issues/22#issuecomment-150839683) of downgrading electron from the current master is roughly what I tried [here](https://github.com/twolfson/google-music-electron/issues/22#issuecomment-150824938).  I edited package.json directly, because I am ignorant, but I _think_ it was effectively the same.

So I started trying my patched dbus, based on your second comment.  I ran into trouble on the `node install` in mpris-service -- it immediately tried to build the official dbus. If I `npm link dbus` first, to pull mine into mpris-service/node_modules/dbus, then everything seems fine.

I then made it up to the `./node_modules/electron-rebuild/lib/cli.js` step, and then ran into nan errors building nslog@2.0.0.  That also uses an old nan, so I'll see about upgrading that.

Onward.

**Comment by rossabaker** [comment] 2015-10-24 20:11
Progress.  I sidestepped the nslog build failure with the newer electron-rebuild:

```
npm install --ignore-scripts --save false electron-rebuild@~1.0.2 mpris-service@~1.0.1
```

I am now running 2.0.1, with an mpris interface!  The uncaught errors I saw in 1.20.0 are gone from the logs...

```
2015-10-24T20:06:03.103Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "/home/ross/.config/google-music-electron/verbose.log"
2015-10-24T20:06:03.217Z - info: App ready. Opening Google Music window height=920, icon=/home/ross/src/personal/google-music-electron/lib/assets/icon-32.png, preload=/home/ross/src/personal/google-music-electron/lib/browser.js, skip-taskbar=undefined, use-content-size=true, width=1024, http_parser=2.5.0, node=4.1.1, v8=4.5.103.29, uv=1.7.4, zlib=1.2.8, ares=1.10.1-DEV, modules=46, openssl=1.0.2d, electron=0.34.1, atom-shell=0.34.1, chrome=45.0.2454.85, version=2.0.1
```

... but the mpris metadata still doesn't populate:

```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.google-music-electron /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'
method return time=1445717407.200952 sender=:1.267 -> destination=:1.297 serial=32 reply_serial=2
   variant       array [
      ]
```

**Comment by twolfson** [comment] 2015-10-24 20:47
Afk at the moment but I will try to facilitate via email.

With respect to older versions of google-music-electron, can you downgrade
to 1.19.0 as a sanity check? It will give us a point of reference where we
know everything is stable.

With respect to fixing whatever is broken, the progress you have made
sounds great. It's hard to tell what exactly broke; the bindings in dbus to
node or something in mpris service to dbus.

Unfortunatley, my knowledge falls short here. But I believe seeing a major
version release in mpris service try upgrading to that (or downgrading to
our older version if git is using master).

**Comment by rossabaker** [comment] 2015-10-25 02:09
Okay.  Switching to Node 4.1.1, so as not to tempt fate with Electron.

Downgraded to google-music-electron 1.19.0 (which I see uses node 1.6.3).  It looks a lot like 1.20.0: mpris installs, I get an uncaught error, mpris doesn't work:

```
2015-10-25T01:49:27.154Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "/home/ross/.config/google-music-electron/verbose.log"
2015-10-25T01:49:27.450Z - info: App ready. Opening Google Music window height=920, preload=/home/ross/.nvm/versions/node/v4.1.1/lib/node_modules/google-music-electron/lib/browser.js, skip-taskbar=undefined, use-content-size=true, width=1024, http_parser=2.3.0, node=1.6.3, v8=4.2.77.15, uv=1.4.2, zlib=1.2.8, ares=1.10.0-DEV, modules=43, openssl=1.0.1m, electron=0.26.1, atom-shell=0.26.1, chrome=42.0.2311.107, version=1.19.0
[21614:1024/214942:INFO:CONSOLE(443)] "Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.", source: /home/ross/.nvm/versions/node/v4.1.1/lib/node_modules/google-music-electron/node_modules/google-music/lib/main.js (443)
```

Back to 2.0.1.  I dug into lib/browser.js.  I noticed none of my stdout.writes worked after `var googleMusic = new GoogleMusic(window);`.  I added a catch block with an OOPS prefix, and sure enough:

```
OOPS NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null.
```

If `handleLoad` doesn't run to completion, the unresponsive mpris interface makes sense, because the ipc handlers are not set up.  This same problem that spurred me to upgrade still exists, but is just hidden better now.

And now I'm back in over my head. :)

**Comment by rossabaker** [comment] 2015-10-25 18:26
Eureka!  GoogleMusic is selecting `sj-icon-button`, but the element has changed to `paper-icon-button`.  This is probably why it's broken across all versions.  I now have a working mpris again locally.  I'll send a PR to the other library later tonight.

I don't know why the GoogleMusic exception is no longer bubbling to the console, but I speak a lot of languages, and JavaScript isn't one. :smile:

**Comment by twolfson** [comment] 2015-10-25 22:04
Weird, I see `sj-icon-button` still o_O

![selection_187](https://cloud.githubusercontent.com/assets/902488/10718144/92cf00d4-7b39-11e5-9c48-e3292631dfbc.png)

I totally missed the `MutationObserver` errors earlier on -_-;; This was an issue in the first few revisions but I thought we patched it via the `addEventListener('load'`.

The gist of the problem with `MutationObserver` is we are encountering a race condition. The Google Music UI is loading at the same time we are telling `google-music.js` to initialize, find elements on the page, and bind to them. Unfortunately, `google-music.js` is running faster than the elements exist so it's finding `null` and trying to bind to that. Hence: `The provided node was null.`

This also should explain why it's being spotty when you change versions. Sometimes Google Music runs earlier, sometimes `google-music.js` does. I will look into throttling my internet so I can reproduce and hopefully fix it for good.

**Comment by twolfson** [comment] 2015-10-25 22:19
We are successfully reproducing via Charles Proxy with throttling at 512 kbps and forcing `electron` to not use disk cache:

``` bash
node bin/google-music-electron.js --proxy-server="localhost:8888" --disable-http-cache
```

**Comment by twolfson** [comment] 2015-10-25 22:42
Okay, that's really weird. My test account inside of `google-music.js` is getting `paper-icon-button` but my normal account in `google-music-electron` is getting `sj-icon-button`. I am guessing they are A/B testing new UI's?

**Comment by twolfson** [comment] 2015-10-25 23:54
Alright, the `MutationObserver` issue should be resolved in `2.1.0`. Here are the corresponding changes:
- Loosened up selectors in `google-music.js@3.2.0` to match both `sj-icon-button` and `paper-icon-button`
- Added assertions for all elements existing when we initially select them (this allows us to make nice try/catch's on init)
- Added `setTimeout` loop with try/catch when we attempt to bind `google-music.js`
  - In less JS-centric terms, it's a retry loop every 1 second, up to 60 seconds

**Comment by rossabaker** [comment] 2015-10-26 00:16
Very nice!  Your A/B theory rings true.  I am now fully operational with:
- google-music-electron 2.1.0
- my patched dbus
- electron-rebuild-1.0.2 to get past more nan compilation errors in nslog.

**Comment by twolfson** [comment] 2015-10-26 01:25
Woo hoo! I'm going to leave this issue open until `dbus` and `mpris-service` are patched for our version of `electron`. Thanks for all the help on this =)

**Comment by twolfson** [comment] 2015-10-27 01:00
Yay, your PR has been landed. I am going to submit a PR for `mpris-service` to use the patched `dbus` =)

**Comment by twolfson** [comment] 2015-10-27 01:02
Oh, never mind. `mpris-service` uses a minor-loose dependency for `dbus` so it should be picked up automatically.

https://github.com/emersion/mpris-service/blob/9a35f9d94cf88cb2cec179d9f4bc1caa6bc9eb3a/package.json#L26

I am going to create a new `google-music-electron` release with the upgraded `electron-rebuild` though =)

**Comment by twolfson** [comment] 2015-10-27 01:08
Alright, we should be all said and done. I have updated `mprisDependencies` to use `electron-rebuild@1.0.2` in `2.1.1` and the `dbus` patch has been picked up upon reinstall. Once again, thanks for all your help =)

**Closed as completed by twolfson** 2015-10-27 01:08 UTC
Labels: bug, blocked

**Comment by rossabaker** [comment] 2015-10-27 03:16
Fixes confirmed from a clean nvm install.  Thanks for helping a newbie, and the quick release.
