### ISSUE TITLE
Do not open more than one instance of google music electron

### ISSUE THREAD

**Issue by AngelEzquerra** [twolfson/google-music-electron#19] opened 2015-10-21 14:11 UTC
Executing google music electron when it is already running should not open a new instance. Instead it should just show (unhide and bring to the front) the existing instance.

**Comment by AngelEzquerra** [comment] 2015-10-21 14:14
Also, it would be neat if you could pass an "action" should as play, plause, next and prev. In that case the window should not be shown, but the action should be performed (silently).

**Comment by twolfson** [comment] 2015-10-21 19:09
We decide to allow multiple instances to make our life as developers easier (e.g. listen to music in one instance, reboot/dev in another). Considering this a `wontfix` for now.

**Comment by twolfson** [comment] 2015-10-21 19:10
With respect to actions, those integrations can be done via something like MPRIS. Here's a CLI tool that makes calls out to MPRIS and should work:

https://github.com/acrisci/playerctl

**Comment by AngelEzquerra** [comment] 2015-10-21 21:04
I think MPRIS only works on Linux?
Also, would you consider adding a flag to avoid opening more than one instance?

**Comment by twolfson** [comment] 2015-10-21 21:24
With respect to MPRIS, I think you are right about it being Linux only. I have a feeling there are Windows equivalents though. Worst case scenario, I would opt for an HTTP API over CLI integration (since the latter would likely need an API inevitably).

With respect to multiple instances, we will have to research if that's possible. I know `nw.js` had something about `singleInstance` -- maybe we can reproduce what they do (e.g. if they do something like find similarly named processes)

**Comment by twolfson** [comment] 2015-10-22 02:43
It looks like this should be possible via a module named `monogamous` and eventually maybe `electron` itself:

https://github.com/atom/electron/issues/648

https://github.com/mnichols/monogamous

**Comment by twolfson** [comment] 2015-10-23 04:41
To give an ETA on this, I will try implementing this by the end of next weekend (unless someone beats me to the punch).

**Comment by twolfson** [comment] 2015-10-24 04:27
Taking a look at building this now. Going to make single instance the default with a CLI flag/config override to enable multiple instances.

**Comment by twolfson** [comment] 2015-10-24 04:50
This has been implemented in `2.0.0`.

**Closed as completed by twolfson** 2015-10-24 04:50 UTC
Labels: enhancement, help wanted

**Comment by AngelEzquerra** [comment] 2015-10-26 12:44
This is really neat. Thank you!!!
